<?php

/**
 * Implements hook_menu()
 */
function sportsfan_menu() {
	return array(
		'fan' => array(
			'title' => 'Sports Fan Home',
			'page callback' => 'sportsfan_home',
			'file' => 'sportsfan.page.inc',
			'access callback' => TRUE,
		),
	);
}

/**
 * Implements hook_theme()
 */
function sportsfan_theme() {
	return array(
	);
}

/**
 * Implements hook_block_info()
 */
function sportsfan_block_info() {
	// allow sportsevent, pickem, team modules to add custom blocks that 
	// can be published by the sportsfan module
	$sportsfan_custom_block_info = module_invoke_all('sportsfan_block_info');

	return array(
	) + $sportsfan_custom_block_info;
}
