<?php

/**
 * Implements hook_menu()
 */
function venue_menu() {
	return array(
		'admin/config/venues' => array(
			'title' => t('Athletic Venue Management'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('venue_admin_venue_default'),
			'access arguments' => array('administer site configuration'),
			'file' => 'venue.admin.inc',
		),
		'admin/config/venues/add' => array(
			'title' => t('Add Venue'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('venue_admin_venue_form'),
			'access arguments' => array('administer site configuration'),
			'file' => 'venue.admin.inc',
			'type' => MENU_DEFAULT_LOCAL_TASK,
		),
		'admin/config/venues/edit/%venue' => array(
			'page callback' => 'venue_admin_venue_form',
			'file' => 'venue.admin.inc',
		),
		'admin/config/venues/capacity/add' => array(
			'page callback' => 'venue_admin_venue_capacity_form',
			'file' => 'venue.admin.inc',
		),
		'admin/config/venues/capacity/%venue_capacity/edit' => array(
			'page callback' => 'venue_admin_venue_capacity_form',
			'file' => 'venue.admin.inc',
		),
	);
}

function venue_entity_info() {
	return array(
		'venue' => array(
			'label' => t('Venue'),
			'label callback' => 'venue_label_callback',
			'plural label' => t('Venues'),
			'entity class' => 'Venue',
			'controller class' => 'VenueController',
			'base table' => 'venue',
			'fieldable' => TRUE,
			'entity keys' => array(
				'id' => 'vid'
			),
			'load hook' => 'venue_load',
			'admin ui' => array(
				'path' => 'admin/content/venues',
				'controller class' => 'VenueUIController',
				'file' => 'includes/venue.admin.inc',
			),
			'bundles' => array(
				'team' => array(
					'label' => 'Venue',
					'admin' => array(
						'path' => 'admin/structure/venue/manage',
						'access arguments' => array('administer venue entities'),
					),
				),
			),
			'module' => 'venue',
			'access callback' => 'venue_access_callback',
			'static cache' => TRUE,
			'uri callback' => 'entity_class_uri',
		),
	);	
}

/**
 * Team access callback.
 */
function venue_access_callback() {

  if (user_is_anonymous() || !user_access('administer venue entities')) {
    return FALSE;
  }
  else {
    return TRUE;
  }

}

// LABEL CALLBACKS
/**
 * Label callback for team entities
 */
function venue_label_callback($venue, $type = NULL) {
	return empty($venue->name) ? 'Untitled Venue' : $venue->title;	
}

/**
 * URI Callback for Team
 */
function venue_basic_uri($venue) {
	return array(
		'path' => sprintf('venue/%s/%s', $venue->sport, $venue->vid),
	);
}

/**
 * Menu autoloader for /team.
 */
function venue_load($venue_id, $reset = FALSE) {
  $venue = venue_load_multiple(array($venue_id), array(), $reset);
  return reset($venue);
}

/**
 * Load multiple team based on certain conditions.
 */
function venue_load_multiple($venue_ids = FALSE, $conditions = array('active' => 1), $reset = FALSE) {
  return entity_load('venue', $venue_ids, $conditions, $reset);
}
